### PR TITLE
fix rings

### PR DESCRIPTION
**Pull request by CJEnright**
Screen Shot 2020-10-18 at 19 12 53

@albertzhong123 I had to delete the background image for the surfboards to get this right, but I can't figure out Figma for the life of me (it really doesn't like exporting the sand wave?) Can you get that background image from design but without the rings in it?

Or, better yet, you could probably export the entire section from below the rings to above the FAQ as a single SVG...

### CODE REVIEW

**Comment by albertzhong123** [comment]
I'm not sure if you mean the background images w/o rings and surfboards or just w/o rings, but the Website Assets folder should have both. It's under the design folder in the google drive

**Comment by CJEnright** [comment]
@albertzhong123 This look good? If so pls approve

**Comment by albertzhong123** [comment]
Everything looks good, but it looks like the color of the sand from the surfboard and the color from the faq differs
Screen Shot 2020-10-20 at 4 03 38 PM

**Comment by CJEnright** [comment]
Are you checked out at `489d863`? Because that commit should've fixed it

**Review by albertzhong123 — APPROVED** [review]

**Pull request merged**
